### PR TITLE
Create C

### PR DESCRIPTION
**Pull request by herambchaudhari4121**
hi  Didi pls accept my PR

### CODE REVIEW

**Comment by herambchaudhari4121** [comment]
pls accept fast I have less time to complete hacktoberfest

**Comment by herambchaudhari4121** [comment]
hope u may like my pull request. thanking in advanced for merging it

**Comment by Shivani1337** [comment]
Hey,
Sorry to say but this PR is not acceptable even if I merged this PR then after 14days it will be rejected.
So, read all the rules before creating PR.

**Comment by herambchaudhari4121** [comment]
Didi accept it may it was possible that they my accept a after 14 days. me bas enta kena chata hu ki aap accept kar  do syaad vo In Progress se pr accept kar le try karne kay jaata hai 😅😀by the way happy Diwali in advance

**Pull request merged**
